version: "3.7"

services:
  english-calificator:
    build:
      context: .
      dockerfile: ./Docker/prod/Dockerfile
    image: english-calificator
    container_name: english-calificator-dev
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    labels:
      - "traefik.http.routers.english-calificator.rule=Host(`omegahealtycare.datarobotix.com`)"
